# /netlify.toml  (repo root)

[build]
  command = "npm install --no-audit --no-fund && npm run build"
  publish = "dist"

[[redirects]]
  from = "/api/*"
  to   = "https://boardbased-backend.onrender.com/:splat"
  status = 200
  force  = true

[[redirects]]
  from = "/*"
  to   = "/index.html"
  status = 200
